permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

kramdown:
  input: GFM

# 作者信息
author: 
  name: Ivan
  email: dcty@qq.com
  link: http://ivan.meiyou.im
  weibo: http://weibo.com/1860755332
  github: http://github.com/dcty

# 站点信息
title: Ivan's Blog
description: Ivan's Blog
url: http://ivan.meiyou.im
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://tp1.sinaimg.cn/1860755332/180/5713529460/1
favicon: http://img.seeyouyima.com/shenmiao/images/favicon.ico

# google analytics 设置
ga:
  id: UA-65583419-1
  url: ivan.meiyou.im

# disqus 设置
disqus:
  shortname: dcty